### ISSUE TITLE
Circomspect doesn't recognize the syntax of a valid circom file.

### ISSUE THREAD

**Issue by ytrezq** [trailofbits/circomspect#5]
I have a file which looks like this at the beginning

    include "../node_modules/circomlib/circuits/poseidon.circom";
    include "./merkleProof.circom"
    include "./keypair.circom" 

but when I analyse it, it gives

    # circomspect transaction.circom
    error: UnrecognizedToken { token: (93, Token(61, "include"), 100), expected: ["\")\"", "\",\"", "\";\""] }                                                                  
      ┌─ /home/user/cash/circuits/transaction.circom:3:1
      │ 
    3 │ include "./keypair.circom"
      │ ^^^^^^^ Invalid syntax

    circomspect: 1 issue found.
However, the same file does compiles fine using `npx circom -v` without giving other input files or input settings on the command line.

**Comment by ytrezq** [comment]
@fegge maybe because it s about a language variant no supported yet? The files are compiled to Solidity.

**Comment by ytrezq** [comment]
@fegge even if I add `;` despite the fact it should work as is, then it complains at the keyword telling the variable is a parameter to the function

    28 │     signal private input inAmount[nIns];
       │                    ^^^^^ Invalid syntax

**Comment by fegge** [comment]
The syntax `signal private input inAmount[nIns];` suggests you are using Circom 1 since the `private` keyword is not supported by Circom 2. The developers have deprecated the Circom 1 language and compiler (see [here](https://github.com/iden3/circom_old)), and they suggest that all new projects use the [Circom 2 compiler](https://github.com/iden3/circom) written in Rust.

There are a few differences between Circom 1 and 2. (For example, public and private inputs are specified differently in Circom 2.) Circomspect only supports Circom 2, and we currently have no plans to add support for Circom 1.

**Comment by fegge** [comment]
I'm going to close this issue. If you feel that my comment above missed the mark, feel free to open a new issue.

**Comment by ytrezq** [comment]
@fegge : just an additional question : can Num2bits be used to guard against all negative numbers or is there negative numbers that will pass depending on the value of the input parameter ?
